#! /usr/bin/env bash

set -eu

PROJECT_PATH=`pwd`
APP_NAME=
APP=

function getIntelliJApp() {
  ls -1d /Applications/IntelliJ\ * | tail -n1
}

function getWebstormApp() {
  ls -1d /Applications/WebStorm* | tail -n1
}

function getPhpStormApp() {
  ls -1d /Applications/PhpStorm* | tail -n1
}

function getRubyMineApp() {
  ls -1d /Applications/RubyMine* | tail -n1
}

function getAndroidStudioApp() {
  ls -1d /Applications/Android\ Studio* | tail -n1
}

function getPyCharmApp() {
    ls -1d /Applications/PyCharm* | tail -n1
}

function calcApplication() {
  if [ -f "${PROJECT_PATH}/pom.xml" ]; then
    APP=$(getIntelliJApp)
    return 0
  fi
  if [ -f "${PROJECT_PATH}/Gemfile" ]; then
    APP=$(getRubyMineApp)
    return 0
  fi
  if [ -f "${PROJECT_PATH}/app/src/main/AndroidManifest.xml" ]; then
    APP=$(getAndroidStudioApp)
    return 0
  fi
  if [ -f "${PROJECT_PATH}/settings.gradle" ]; then
    APP=$(getAndroidStudioApp)
    return 0
  fi
  if [ -f "${PROJECT_PATH}/package.json" ]; then
    APP=$(getWebstormApp)
    return 0
  fi
  if [ -f "${PROJECT_PATH}/requirements.txt" ]; then
    APP=$(getPyCharmApp)
    return 0
  fi
  if [ -f "${PROJECT_PATH}/wp-login.php" ]; then
    APP=$(getPhpStormApp)
    return 0
  fi
  if [ -f "${PROJECT_PATH}/composer.json" ]; then
    APP=$(getPhpStormApp)
    return 0
  fi
  if [ -f "${PROJECT_PATH}/index.php" ]; then
    APP=$(getPhpStormApp)
    return 0
  fi

  IML_FILE=`find . -name "*.iml" | tail -n1`
  if [ -f "${IML_FILE}" ]; then
    IML_MODULE=`sed -n 's/JAVA_MODULE/&/p' ${IML_FILE}`
    if [ ${#IML_MODULE} -gt 0 ]; then
      APP=$(getIntelliJApp)
      return 0
    fi

    IML_MODULE=`sed -n 's/WEB_MODULE/&/p' ${IML_FILE}`
    if [ ${#IML_MODULE} -gt 0 ]; then
      APP=$(getWebstormApp)
      return 0
    fi
  fi
}

function getApplication() {
  if [ -z "$APP_NAME" ]; then
    calcApplication
  else
    if [[ $APP_NAME == *ntelli* ]]; then
      APP=$(getIntelliJApp)
    elif [[ $APP_NAME == *ebstorm* ]]; then
      APP=$(getWebstormApp)
    elif [[ $APP_NAME == *hpstorm* ]]; then
      APP=$(getPhpStromApp)
    elif [[ $APP_NAME == *uby* ]]; then
      APP=$(getRubyMineApp)
    elif [[ $APP_NAME == *android* ]]; then
      APP=$(getAndroidStudioApp)
    elif [[ $APP_NAME == *pycharm* ]]; then
      APP=$(getPyCharmApp)
    fi
  fi

  if [ -z "$APP" ]; then
    APP=$(getIntelliJApp)
  fi
}

function verifyIdeaFolder() {
  if [ -d "${PROJECT_PATH}/.idea" ]; then
    return 0
  fi

  read -p "${PROJECT_PATH} is not an idea folder. Sure to open? Y/N: "
  case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
    y|yes) return 0 ;;
    *) return -1
  esac
}

while getopts a: opts; do
  case ${opts} in
    a) APP_NAME=${OPTARG} ;;
  esac
done

verifyIdeaFolder
getApplication
echo "Open $APP..."
open -a "$APP" .

